BEGIN TRANSACTION;
DROP TABLE IF EXISTS "watering";
CREATE TABLE IF NOT EXISTS "watering" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"date"	TEXT NOT NULL,
	"plant"	INTEGER NOT NULL,
	"waterAmount"	REAL NOT NULL,
	FOREIGN KEY("plant") REFERENCES "plant"("id")
);
DROP TABLE IF EXISTS "moistureRead";
CREATE TABLE IF NOT EXISTS "moistureRead" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"date"	TEXT NOT NULL,
	"plant"	INTEGER,
	"moisture"	INTEGER NOT NULL,
	FOREIGN KEY("plant") REFERENCES "plant"("id")
);
DROP TABLE IF EXISTS "plant";
CREATE TABLE IF NOT EXISTS "plant" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"name"	TEXT NOT NULL,
	"description"	TEXT,
	"buyDate"	TEXT,
	"deathDate"	TEXT
);
DROP TABLE IF EXISTS "temperatureRead";
CREATE TABLE IF NOT EXISTS "temperatureRead" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"temperature"	REAL NOT NULL,
	"type"	TEXT NOT NULL,
	"date"	TEXT NOT NULL
);
DROP TABLE IF EXISTS "humidityRead";
CREATE TABLE IF NOT EXISTS "humidityRead" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"humidity"	REAL NOT NULL,
	"type"	TEXT NOT NULL,
	"date"	TEXT NOT NULL
);
COMMIT;
